name: Execute SSH Command Daily

on:
  schedule:
    # Runs every day at 8:00 AM Beijing Time (UTC+8)
    - cron: '0 0 * * *'

jobs:
  run-ssh-command:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Run SSH Command
      run: |
        sshpass -p 'nidGQPJnCsNvPkdhvyy0' ssh -o StrictHostKeyChecking=no hjz888@s8.serv00.com 'cd ~/domains/hjz888.serv00.net/vless && ./check_vless.sh'
      env:
        SSHPASS: ${{ secrets.SSH_PASS }}
