name: Execute SSH Command Daily

on:
  schedule:
    # Runs every day at 8:00 AM Beijing Time (UTC+8)
    - cron: '0 0 * * *'
  
  # Add this section to enable manual triggering
  workflow_dispatch:

jobs:
  run-ssh-command:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client sshpass

    - name: Run SSH Command
      run: |
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$NAME"@s8.serv00.com "$COMMAND"
      env:
        NAME: ${{ secrets.NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        COMMAND: ${{ secrets.COMMAND }}
